CREATE DATABASE Brukersys;
USE Brukersys;

CREATE TABLE Users (id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(15) UNIQUE, passwd VARCHAR(150), enabled BOOL);
CREATE TABLE UKeys (userID INT UNIQUE, ukey CHAR(44), FOREIGN KEY (userID) REFERENCES Users(id));
CREATE TABLE Administrators (userID INT UNIQUE, FOREIGN KEY (userID) REFERENCES Users(id));
CREATE TABLE TempPasswords (userID INT UNIQUE, passwd VARCHAR(20), expires DATETIME, FOREIGN KEY (userID) REFERENCES Users(id));
CREATE TABLE Log (id INT AUTO_INCREMENT PRIMARY KEY, userID INT, what VARCHAR(30), otherID INT, timedone DATETIME, FOREIGN KEY (userID) REFERENCES Users(id));
